baseURL = "http://bandarlog.co.uk/"
languageCode = "en-GB"
title = "1st Bandar-log"
theme = "bandarlog"
enableRobotsTxt = true
enableGitInfo = true
googleAnalytics = "dev"

[permalinks]
  mascot = "/:slug/"

[Params.Author]
  Name = "Phill Sparks"
  Homepage = "https://phills.me.uk/"
  Facebook = "sparks.phill"
  Twitter = "PhillSparks"