baseURL = "http://bandarlog.co.uk/"
languageCode = "en-GB"
title = "Bandar Log"
theme = "bandarlog"
enableRobotsTxt = true
enableGitInfo = true
googleAnalytics = "dev"

[permalinks]
  mascot = "/:slug/"

[Params.Author]
  Name = "Phill Sparks"
  Homepage = "https://phills.me.uk/"