[build]
  publish = "public"
  command = "hugo -b $URL"

[build.environment]
  HUGO_VERSION = "0.72.0"

[context.deploy-preview]
  command = "hugo --i18n-warnings --buildDrafts -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --i18n-warnings --buildDrafts -b $DEPLOY_PRIME_URL"
