[build]
  publish = "public"
  command = "hugo -b $URL"

[build.environment]
  HUGO_VERSION = "0.36.1"

[context.deploy-preview]
  command = "hugo --i18n-warnings -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_GOOGLEANALYTICS = "off"

[context.branch-deploy]
  command = "hugo --i18n-warnings --buildDrafts -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_GOOGLEANALYTICS = "off"