name = "Bandarlog"
license = "MIT"
licenselink = "https://github.com/sparksp/bandarlog.co.uk/blob/master/themes/bandarlog/LICENSE.md"
description = ""
homepage = "http://bandarlog.co.uk/"
tags = []
features = []
min_version = "0.44"

[author]
  name = "Phill Sparks"
  homepage = "https://phills.me.uk/"
